# Project Introduction to data science

Read & clean data

In [37]:
# Load all dependencies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.formula.api as sm
%matplotlib inline

In [38]:
greenhouseEmission = pd.read_csv('/Users/larsboesch/Desktop/FS22/DataScience/project/datascience/original_data/greenhouseGasEmission.csv')

In [39]:
deathRiskFactor = pd.read_csv('/Users/larsboesch/Desktop/FS22/DataScience/project/datascience/original_data/outdoorAirPollution/number-of-deaths-by-risk-factors.csv', sep=';')

In [40]:
new_df = pd.merge(greenhouseEmission, deathRiskFactor,  how='left', left_on=['country','year'], right_on = ['Entity','Year'])

In [41]:
new_df.head()

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
new_df.to_csv('pollution_riskfactor.csv')

In [42]:
regions = new_df[(new_df["country"]).isin(["Africa", "Asia", "China", "India", "Europe", "North America", "United States", "Oceania", "South America"])]
regions

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
72,NaN,Africa,1884,0.022,0.005,NaN,NaN,NaN,0.022,0.005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,Africa,1885,0.037,0.008,NaN,NaN,NaN,0.037,0.008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,Africa,1886,0.048,0.010,NaN,NaN,NaN,0.048,0.010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,Africa,1887,0.048,0.010,NaN,NaN,NaN,0.048,0.010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,Africa,1888,0.081,0.017,NaN,NaN,NaN,0.081,0.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24050,USA,United States,2016,5248.024,16.247,328.696,39.439,0.122,1379.744,4.271,...,369396.0,682.0,922.0,93918.0,26716.0,0.0,16.0,5.0,80.0,144.0
24051,USA,United States,2017,5207.751,16.020,343.021,40.324,0.124,1338.667,4.118,...,373207.0,665.0,929.0,98621.0,26397.0,0.0,15.0,5.0,78.0,126.0
24052,USA,United States,2018,5375.491,16.434,351.120,38.971,0.119,1283.532,3.924,...,384191.0,675.0,958.0,101471.0,27006.0,0.0,15.0,5.0,76.0,120.0
24053,USA,United States,2019,5255.816,15.972,369.967,40.896,0.124,1098.854,3.339,...,393859.0,682.0,987.0,104736.0,27681.0,0.0,14.0,5.0,75.0,114.0
24054,USA,United States,2020,4712.771,14.238,NaN,40.795,0.123,888.649,2.685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
above_1989 = regions[regions["year"] > 1989]

In [46]:
above_1989.to_csv('pollution_riskfactor_cleaned.csv')

In [44]:
df_final = above_1989[["country", "year", "co2", "co2_per_capita", "population", "Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)"]]

In [45]:
df_final

,country,year,co2,co2_per_capita,population,Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number),...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
178,Africa,1990,659.295,1.052,630349685.0,169060.0,517225.0,53910.0,84581.0,181775.0,...,197605.0,657254.0,502767.0,9417.0,17678.0,111243.0,336431.0,12498.0,194374.0,20760.0
179,Africa,1991,689.026,1.068,647344041.0,173284.0,530279.0,54726.0,86492.0,185915.0,...,204707.0,668571.0,510534.0,11493.0,18251.0,110511.0,337791.0,12756.0,199186.0,20850.0
180,Africa,1992,668.677,1.010,664512034.0,177903.0,546003.0,55717.0,88607.0,190333.0,...,213102.0,658974.0,508564.0,14132.0,18769.0,108260.0,335429.0,12510.0,195331.0,21114.0
181,Africa,1993,708.858,1.043,681869333.0,183152.0,561036.0,56454.0,91107.0,192704.0,...,220730.0,654419.0,508280.0,17110.0,19173.0,106062.0,332856.0,12357.0,193919.0,21230.0
182,Africa,1994,719.623,1.029,699445412.0,188664.0,578231.0,57345.0,93391.0,197211.0,...,230701.0,665805.0,516586.0,20653.0,19740.0,105402.0,332387.0,12335.0,194972.0,21476.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24050,United States,2016,5248.024,16.247,323015992.0,60202.0,465558.0,45408.0,95347.0,132508.0,...,369396.0,682.0,922.0,93918.0,26716.0,0.0,16.0,5.0,80.0,144.0
24051,United States,2017,5207.751,16.020,325084758.0,58113.0,467248.0,45805.0,96267.0,133096.0,...,373207.0,665.0,929.0,98621.0,26397.0,0.0,15.0,5.0,78.0,126.0
24052,United States,2018,5375.491,16.434,327096263.0,59375.0,481551.0,47379.0,99502.0,135290.0,...,384191.0,675.0,958.0,101471.0,27006.0,0.0,15.0,5.0,76.0,120.0
24053,United States,2019,5255.816,15.972,329064917.0,60572.0,495201.0,48501.0,102247.0,136663.0,...,393859.0,682.0,987.0,104736.0,27681.0,0.0,14.0,5.0,75.0,114.0
24054,United States,2020,4712.771,14.238,331002647.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df_final.to_csv('airPollution_riskfactor_final.csv')

In [46]:
df_final = df_final.dropna()

In [48]:
columns = ["Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)", "Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)"]

for column in columns:
    df_final[f'rate {column}'] = df_final[column]/df_final["population"]*100000

/var/folders/wm/1qpgw0fn48vfx4dhdfvj7klc0000gn/T/ipykernel_20311/1779097251.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[f'rate {column}'] = df_final[column]/df_final["population"]*100000

In [49]:
df_final

,country,year,co2,co2_per_capita,population,Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number),...,rate Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),rate Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
178,Africa,1990,659.295,1.052,630349685.0,169060.0,517225.0,53910.0,84581.0,181775.0,...,31.348473,104.268157,79.760014,1.493933,2.804475,17.647824,53.372122,1.982709,30.835900,3.293410
179,Africa,1991,689.026,1.068,647344041.0,173284.0,530279.0,54726.0,86492.0,185915.0,...,31.622597,103.279085,78.865946,1.775408,2.819366,17.071448,52.181063,1.970513,30.769728,3.220853
180,Africa,1992,668.677,1.010,664512034.0,177903.0,546003.0,55717.0,88607.0,190333.0,...,32.068945,99.166601,76.531947,2.126673,2.824479,16.291654,50.477491,1.882584,29.394652,3.177369
181,Africa,1993,708.858,1.043,681869333.0,183152.0,561036.0,56454.0,91107.0,192704.0,...,32.371305,95.974253,74.542141,2.509278,2.811829,15.554593,48.815218,1.812224,28.439320,3.113500
182,Africa,1994,719.623,1.029,699445412.0,188664.0,578231.0,57345.0,93391.0,197211.0,...,32.983417,95.190416,73.856514,2.952768,2.822236,15.069368,47.521507,1.763540,27.875228,3.070433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24049,United States,2015,5371.771,16.741,320878312.0,62621.0,456936.0,44306.0,93765.0,128082.0,...,112.085793,0.220644,0.286090,26.654653,8.171634,0.000000,0.004986,0.001558,0.024932,0.043007
24050,United States,2016,5248.024,16.247,323015992.0,60202.0,465558.0,45408.0,95347.0,132508.0,...,114.358425,0.211135,0.285435,29.075341,8.270798,0.000000,0.004953,0.001548,0.024767,0.044580
24051,United States,2017,5207.751,16.020,325084758.0,58113.0,467248.0,45805.0,96267.0,133096.0,...,114.802983,0.204562,0.285772,30.337011,8.120036,0.000000,0.004614,0.001538,0.023994,0.038759
24052,United States,2018,5375.491,16.434,327096263.0,59375.0,481551.0,47379.0,99502.0,135290.0,...,117.455026,0.206361,0.292880,31.021755,8.256285,0.000000,0.004586,0.001529,0.023235,0.036686
24053,United States,2019,5255.816,15.972,329064917.0,60572.0,495201.0,48501.0,102247.0,136663.0,...,119.690365,0.207254,0.299941,31.828370,8.412018,0.000000,0.004254,0.001519,0.022792,0.034644

In [50]:
df_final.to_csv('airPollution_riskfactor_final_rates.csv')